name: $(BuildID)
trigger:
  branches:
    include:
      - master

phases:
  - template: .vsts/template.yml
    parameters:
      name: test_linux
      queue: 'Hosted Linux Preview'
  - template: .vsts/template.yml
    parameters:
      name: test_macos
      queue: 'Hosted macOS Preview'
  - template: .vsts/template.yml
    parameters:
      name: test_windows
      queue: 'Hosted VS2017'
  - phase: Release
    queue: 'Hosted VS2017'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - test_linux
      - test_macos
      - test_windows
    steps:
      - bash: npm ci && ./node_modules/.bin/semantic-release
        env:
          NUGET_API_KEY: $(NuGetApiKey)
          GITHUB_TOKEN: $(GitHubToken)
        displayName: Run semantic-release
