queue: 'Hosted Linux Preview'

steps:
- script: |
    cd Source/GitAutomationCore
    dotnet publish -o ../../GitAutomationCore/Assemblies
    cd ../..
- powershell: |
    Install-Module -Force -Scope CurrentUser Pester
    Install-Module -Force -Scope CurrentUser PSCodeCovIo
    $ProgressPreference = "SilentlyContinue"
    $res = Invoke-Pester -PassThru -CodeCoverage . -OutputFile testresults.xml -OutputFormat NUnitXML
    Export-CodeCovIoJson -CodeCoverage $res.CodeCoverage -RepoRoot $pwd -Path coverage.json
    if ($res.FailedCount -gt 0) {
      throw "$($res.FailedCount) tests failed."
    }
- task: PublishTestResults@2
  inputs:
    testRunner: nUnit
    testResultsFiles: 'testresults.xml'
- bash: bash <(curl -s https://codecov.io/bash) -f coverage.json
