
phases:
  - template: .vsts/steps.yml
    parameters:
      name: Linux
      queue: 'Hosted Linux Preview'
  - template: .vsts/steps.yml
    parameters:
      name: macOS
      queue: 'Hosted macOS Preview'
  - template: .vsts/steps.yml
    parameters:
      name: Windows
      queue: 'Hosted VS2017'
